name: realtime_database_todo
description: Todo App With RealTime Database

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  bloc_provider: ^1.0.0
  flutter_bloc: ^8.1.3
  firebase_database: ^10.2.5
  sqflite: ^2.3.0
  path: ^1.8.3
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/rive/